/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aqua;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

  @Test
  public void appHasAGreeting() {
    App classUnderTest = new App();
    assertNotNull(classUnderTest.foo(), "foo1");
    assertEquals(classUnderTest.foo(), "foo");
  }
}
